# Generated by Django 4.2.6 on 2023-10-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_forgot_password_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
