# Generated by Django 4.2.6 on 2023-11-01 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default='', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('pet', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=200)),
                ('selected_service', models.CharField(max_length=200)),
                ('pet_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pickup_location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('drop_location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('instructions', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
