# Generated by Django 4.2.6 on 2023-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactus_alter_appointment_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
