# Generated by Django 4.2.6 on 2023-11-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointment_signature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='owner_sign',
            field=models.ImageField(default='static/img/arth_sign.png', upload_to=''),
        ),
    ]
