# Generated by Django 4.2.6 on 2023-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_service_appointment_selected_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='drop_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pickup_location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
